---

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: rockylinux-lego
    box: "rockylinux/8"
    memory: 2048
    cpus: 2
  - name: rockylinux-lego
    box: "rockylinux/9"
    memory: 2048
    cpus: 2
  - name: fedora-lego
    box: "fedora/37-cloud-base"
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
